# Generated by Django 4.2.7 on 2026-04-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('author', 'Author'), ('convener', 'Convener'), ('reviewer', 'Reviewer'), ('librarian', 'Librarian')], default='author', max_length=20),
        ),
    ]
