# Generated by Django 4.2.7 on 2026-04-17 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_supportrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contributor_emails',
            field=models.TextField(blank=True, help_text='Comma-separated contributor emails (same order as contributors)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='doi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='final_report_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='When convener reminder was last sent to author', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reviewer_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for reviewer to complete review (3 weeks)', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='series_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='series_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='report',
            name='submission_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for author resubmission (4 weeks major / 2 weeks minor)', null=True),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='report',
            field=models.ForeignKey(blank=True, help_text='Leave blank if not related to a specific report', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to='reports.report'),
        ),
    ]
